#!/bin/sh

touch library/x.o

mkdir -p library include source
ln -sf include/* .
for i in `ls source`
do
   j=`basename $i`
   j=${j%.*}
   rm -f library/$j.o
   $PWD/../CompileRootMacro source/$i library/$j.o -c
done

rm -f library/TauHelperFunctions2.o

rm library/x.o
