#!/bin/sh

mkdir -p library include source
ln -s include/* .
for i in `ls source`
do
   j=`basename $i`
   j=${j%.*}
   rm library/$j.o
   $PWD/../CompileRootMacro source/$i library/$j.o -c
done

rm library/TauHelperFunctions2.o
